openapi: 3.0.0
info:
  title: Intent Identification Service
  version: 1.0.0
  description: >-
    A service that identifies user intents based on their questions or
    statements.
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /v1/users/{userId}/intents:
    post:
      summary: Identify user intents
      description: >-
        This endpoint takes a user's question or statement and matches
        predefined intents.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
          example: "12345"
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT token
          example: Bearer your_jwt_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InputText"
      responses:
        "200":
          description: A list of matched intents with their deep links
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IntentsResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerErrorResponse"
  /v1/metrics:
    get:
      summary: Get service metrics
      description: >-
        This endpoint returns metrics data such as the number of times the
        service was called, the number of languages detected, etc.
      responses:
        "200":
          description: Metrics data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricsResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerErrorResponse"
  /v1/actions/suggestions:
    get:
      summary: Get suggested actions
      description: >-
        This endpoint returns suggested actions, which are a few intents mapped
        to a user-friendly question.
      responses:
        "200":
          description: Suggested actions data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestedActionsResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerErrorResponse"
components:
  schemas:
    InputText:
      type: object
      properties:
        inputText:
          type: string
          description: The user's question or statement
          example: I need to block my debit card.
    Intent:
      type: object
      properties:
        intent:
          type: string
          description: The matched intent
          example: block_debit_card
        deepLink:
          type: string
          description: Deep link to the action
          example: AUTH_BLOCK_DEBIT_CRD
    IntentsResponse:
      type: object
      properties:
        intents:
          type: array
          items:
            $ref: "#/components/schemas/Intent"
    BadRequestResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: >-
            Required paramter 'inputText' is missing.
    UnauthorizedResponse:
      type: object
      properties:
        status:
          type: integer
          example: 401
        error:
          type: string
          example: Unauthorized
        message:
          type: string
          example: You are not authorized to access this resource. Please authenticate.
    ForbiddenResponse:
      type: object
      properties:
        status:
          type: integer
          example: 403
        error:
          type: string
          example: Forbidden
        message:
          type: string
          example: You do not have permission to access this resource.
    InternalServerErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        message:
          type: string
          example: >-
            The server encountered an unexpected condition that prevented it
            from fulfilling the request.
    MetricsResponse:
      type: object
      properties:
        totalCalls:
          type: integer
          description: Total number of times the service was called
          example: 1500
        languages:
          type: array
          items:
            type: string
          description: List of languages in which the user asked the question
          example:
            - en
            - es
            - fr
        numberOfLanguages:
          type: integer
          description: Number of unique languages detected
          example: 3
    SuggestedAction:
      type: object
      properties:
        intent:
          type: string
          description: The suggested intent
          example: block_debit_card
    SuggestedActionsResponse:
      type: object
      properties:
        suggestedActions:
          type: array
          items:
            $ref: "#/components/schemas/SuggestedAction"
